name: Парсер мероприятий

on:


  # Возможность запустить вручную кнопкой
  workflow_dispatch:

jobs:
  parser:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить парсер
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          BACKEND_LOGIN: ${{ secrets.BACKEND_LOGIN }}
          BACKEND_PASSWORD: ${{ secrets.BACKEND_PASSWORD }}
        run: python parser.py
